title: Harsh Singhvi # your name (or website title) here
logo: "/images/logohs.png.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  This website in under construction.
  <br><br>
  By the time you can contact me though:-
  <br><br>
  <a href="http://linkedin.com/in/harsh-singhvi-658968a1">View My LinkedIn Profile</a>   
  <br>
  <a href="https://instagram.com/insomniac_coder?igshid=1m2jur72ucxhf">View My Instagram Profile</a> 




theme: jekyll-theme-hacker
google_analytics: UA-141565153-1 # your Google Analytics tracking ID here
